version: '3'
services:
 # 服务名称
  bosch:
    # 容器名称
    container_name: bosch
    # 镜像名称
    image: bosch:v1
    # 暴露的端口号
    ports:
      - "80:80"
      - "30002:30002"
    # 设置权限 ：拥有root权限
    privileged: true

    networks:
      - default


networks:
 default:
  external:
    name: agannet

